### ISSUE TITLE
[UI] Pantalla de login

### ISSUE THREAD

**Issue by ferorus** [Garracuca/AvecinalFCTs#1]
La aplicación tendrá una pantalla inicial con el logo de A Vecinal y un formulario de login

**Comment by kimyLuu** [comment]
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{{ route('login') }}" method="POST">
        @csrf
        <label for="email">Email:</label>
        <input type="email" name="email" required>
        <label for="password">Password:</label>
        <input type="password" name="password" required>
        <button type="submit">Login</button>
    </form>
    <a href="{{ route('register') }}">¿No tienes una cuenta? Regístrate aquí</a>
</body>
</html>
`

**Comment by kimyLuu** [comment]
Esto es en Views login.blade.php

**Comment by kimyLuu** [comment]
`<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrarse</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    <div class="container">
        <h1>Registrarse</h1>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('register') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Nombre</label>
                <input type="text" name="name" required>
            </div>
            <div class="form-group">
                <label for="email">Correo Electrónico</label>
                <input type="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="password_confirmation">Confirmar Contraseña</label>
                <input type="password" name="password_confirmation" required>
            </div>
            <button type="submit">Registrarse</button>
        </form>

        <p>¿Ya tienes cuenta? <a href="{{ route('login') }}">Inicia sesión aquí</a></p>
    </div>
</body>
</html>
`

**Comment by kimyLuu** [comment]
en el fichero views/auth/register.blade.php

**Comment by kimyLuu** [comment]
`<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    // Mostrar formulario de inicio de sesión
    public function showLoginForm()
    {
        return view('auth.login'); // Retorna la vista de login
    }

    // Manejar el inicio de sesión
    public function login(Request $request)
    {
        // Validación de los datos
        $request->validate([
            'email' => 'required|email',
            'password' => 'required',
        ]);

        // Intento de autenticación
        if (Auth::attempt($request->only('email', 'password'))) {
            return redirect()->intended('/home'); // Redirige a la página deseada después del login
        }

        return back()->withErrors([
            'email' => 'Las credenciales son incorrectas.',
        ]);
    }

    // Mostrar formulario de registro
    public function showRegistrationForm()
    {
        return view('auth.register'); // Retorna la vista de registro
    }

    // Manejar el registro
    public function register(Request $request)
    {
        // Validación de los datos
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
        ]);

        // Crear un nuevo usuario
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password), // Asegúrate de cifrar la contraseña
        ]);

        // Intentar iniciar sesión automáticamente después del registro
        Auth::attempt($request->only('email', 'password'));

        return redirect('/home'); // Redirige a la página de inicio después del registro
    }

    // Manejar el cierre de sesión
    public function logout()
    {
        Auth::logout();
        return redirect('/login'); // Redirige a la página de login después de cerrar sesión
    }
}
`
